### ISSUE TITLE
Implement Date Range Feature and new mobile and desktop designs

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-datepicker#106]
## Is your feature request related to a problem? Please describe.

The current auro-datepicker is a single calendar instance. We do not have the ability to easily add multiple calendars within the same UI element in order to create a date range experience. 

## Describe the solution you'd like

The team is to complete a POC of how we can potentially wrap the [wc-date-range](https://www.npmjs.com/package/wc-range-datepicker) 3rd party element into our own experience. 

Looking at this project, we may want to consider supporting some cleaning up of this WC. If the author is unresponsive to these efforts, we will want to consider simply forking this element and adding it directly to Auro. 

The POC is considered done when `wc-date-range` is implemented within `auro-datepicker` and datepicker continues to work as it did before when it was extending Lion Calendar. Once the POC is complete, the work moving forward will consist of adding the date range functionality into `auro-datepicker` as a new feature.

## Other tickets rolled up into this work:
- [x] #105
- [x] #107
- [x] #109 

## POC Exit criteria 
- [x] `auro-calendar` lives in the `auro-datepicker` repo
- [x] `auro-calendar` is based on wc-date-range
- [x] `centralDate` is parsed into `month` and `year` attributes used by `wc-date-range`
- [x] Existing `auro-datepicker` uses new `auro-calendar` with "noRange" attribute (makes it so that there are essentially no new features for users at this point)

## Feature Exit Criteria
- [x] Date range functionality is added
- [x] Validation correctly handles one input for non-date range implementation
- [x] Validation correctly handles two inputs for date range implementation
- [x] Correct number of calendars are displayed on both desktop and mobile given min and max date attribute settings
  - [x] 2 on desktop (current month + 1)
  - [x] 12 on mobile (current month +11)
  - [x] Number of calenders will not include more than exist from `minDate` to `maxDate` - e.g. `minDate === 3/1/2023` and `maxDate === 3/8/2023` will result in only 1 calendar month displayed.
- [x] desktop UI matches Figma blueprint
- [x] mobile UI matches Figma blueprint

## TODO Task List For Tracking Work
- [x] Correctly position the auro-input alert and clear(x) icon
- [ ] Make all tests current and meet coverage threshold
- [ ] Validate a11y with multiple inputs of range support
- [x] prevent calendar navigation before/after min/max date range
- [x] fix first click in calendar (which moves focus) causes validation to run and shows error on required datepicker
- [x] make sure numCalendars is recalculating on resize
- [x] mobile calendar - gradient always overlaps the last months last week
- [x] expose month names as an attribute so localized names can be passed in - use English as default.
- [x] update code to use correct token breakpoints for mobile
- [x] render correct number of calendars when based on min/max date range
- [x] add correct breakpoint number for numCalendars function calculation
- [x] when a return date is typed and then a depart date that is later than the current return date is selected, the return date needs to be reset
- [x] update code to use correct auro size tokens
- [x] Correctly position return date input label when datepicker is open in mobile version 
- [x] Ensure all JS code works correctly for both single selection and date range scenarios
- [x] If minDate is not in centralDate (month viewed on load) move centralDate to minDate
- [x] fix `Invalid time value` console error on first load
- [x] mobile non-range datepicker should hide second date
- [x] setup class export and CE define for custom naming convention
- [x] make sure we are firing all the right events for value change(s) and validation occurrences
- [x] edit day of week and month text layout on mobile
- [x] fully document all examples
- [x] default mobile < button to always show what we have as the hover affect
- [x] Change number color of selected dates on the calendar that are disabled (ex. when a date is typed and is before the min date)

This issue will be considered complete once we have a working POC with a demonstrable version to the team.

**Comment by jordanjones243** [comment]
The `wc-date-range` POC has been completed and validated by the Auro team. The next step will be adding the date range functionality to `auro-datepicker` as a new feature.

**Comment by jason-capsule42** [comment]
The draft PR on this should be fully functional and documented. Remaining work should just be automated testing at this point.
