### ISSUE TITLE
Update to support Node 18||20

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-datepicker#147]
# General Support Request

This repo needs minor updates to be compatible with current Auro Generator standards. The following is a list of things to be considered. 

## Support request

- [x] Update env to support Node 18
- [x] Update to Lit2.0
- [x] Add Typescript support 
- [x] Ensure that all Auro element dependencies work with this element version
- [x] Remove old branch references from testPublish.yml
- [x] Remove unused packages like `marked` and `prism` 
- [x] Update ALL npm packages 
- [x] Update .gitignore
- [x] Update .npmignore 
- [x] Update ISSUE TEMPLATES 
- [x] Update CONTRIBUTING.md
- [x] Remove all IE legacy support 
- [x] Remove all legacy demo build scripts
- [x] Update to support component extension 
- [x] Rebuild all markdown documents based on updates from Generator 
- [x] Ensure that all badges work as expected on README.md
- [x] Update settings.yml
- [x] Install surge demo deployment support 

## Exit criteria 

This issue will be complete once the repo is up to date with the current standards established by the Auro Generator

**Comment by blackfalcon** [comment]
Adding small additional scope to this issue. Update the repo to support `18 || 20` per the new Node support model defined here https://auro.alaskaair.com/node-support
